# 端口
server:
  port: 8090
# 服务设置
spring:
  application:
    name: nacos-provider # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos地址
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *